id: I61345163
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T17:28:58+00:00'
last_modified: '2022-06-07T20:27:36.123147+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5561
  title: མ་ཎི་བཀའ་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A9E4:
      image_group_id: I3CN5563
      title: ''
      total_pages: 576
      order: 1
      base_file: A9E4.txt
    43AF:
      image_group_id: I3CN5564
      title: ''
      total_pages: 476
      order: 2
      base_file: 43AF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
